name: 'lbcreation'

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} 
      # Step 3: Install jq (to parse JSON secret)
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # Step 4: Parse Azure Credentials JSON secret
      - name: Set Azure Credentials
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure.json
          echo "ARM_CLIENT_ID=$(jq -r .clientId azure.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azure.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azure.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenantId azure.json)" >> $GITHUB_ENV

      # Step 5: Terraform Init
      - name: Terraform Init
        working-directory: ./todoapp_infra
        run: terraform init
      - name: Terraform plan
        working-directory: ./todoapp_infra
        run: terraform plan -out=tfplan
